#!/usr/bin/env bash

DT=0.005
EPS=0.25
XSTART=-0.4
NUM=100
METHOD=1 # {0:leapfrog, 1:midpt, 2:simpson}
MHMC=0
LOOPS=1
UPPER=100
LOWER=-100
PRINT=1 # print run parameters on command line

usage() { echo "$0 usage:   [-t dt] [-e eps] [-x xstart] [-n num] [-m method] [-c MHMC] [-L loops] [-u upper] [-l lower] [-d] [-p] [-h]" && echo "" && echo "Detailed help:" && grep " .)\ #" $0 | sed s/\ \#//g ; exit 1; }

while getopts "dpht:e:x:n:m:c:L:u:l:" arg; do
    case "${arg}" in
        h) # print this help
            usage ;;
        d) # run with default parameters
            PRINT=1;;
        p) # suppress run information to stdout
            PRINT=0 ;;
        t) # quadrature time step - dt         : default 0.005
            DT=${OPTARG} ;;
        e) # configurational temperature - eps : default 0.25
            EPS=${OPTARG} ;;
        x) # Initial position - x(0)           : default -0.4
            XSTART=${OPTARG} ;;
        n) # Number of steps - num             : default 100
            NUM=${OPTARG} ;;
        m) # method{0:euler,1:midpt,2:simpson} : default 1
            METHOD=${OPTARG} ;;
        c) # MHMC boolean {0:off,1:on}         : default 0
            MHMC=${OPTARG} ;;
        L) # times to perform the calculation  : default 1
            LOOPS=${OPTARG} ;;
        u) # upper bound for acceptance of path: default 100
            UPPER=${OPTARG} ;;
        l) # lower bound for acceptance of path: default -100
            LOWER=${OPTARG} ;;
        *)
            usage ;;
    esac
done
shift $((OPTIND-1))

if [ $OPTIND -eq 1 ] ; then
    usage
    exit 0
fi

GSL_RNG_SEED=$(shuf -i 2-999999999 -n 1) ./forward_B.out $DT $EPS $XSTART $NUM $METHOD $MHMC $LOOPS $PRINT $UPPER $LOWER 2> /dev/null
